### ISSUE TITLE
Add more customization options

### ISSUE THREAD

**Issue by MagicAndre1981** [SignalGo/SignalGoAddServiceReference-net#1]
Can you please add more customization options?

I don't like that it generates entries with full namespace like `System.Collections.Generic.List<foo>` and would like to have an option to disable this and add using `System.Collections.Generic;` instead and simply use `List<foo>`.

**Comment by Ali-YousefiTelori** [comment]
Hello @MagicAndre1981  and thank you for using signalgo.
Did you mean about generated Reference.cs file with visual studio extension?
In actually signalgo is not care about Reference.cs because its auto generated file and programmers don't need to see what signalgo generated. and I want to khow why you want to have this way, if you explain it for me I will help you.
Why I made this way to generate codes with full namespaces in references.cs?
Because for some reasons if you had 2 models  with same name but different namespace this will fix your errors in references.cs if I use using in top of references.cs file we will get errors in references.cs file.

**Comment by MagicAndre1981** [comment]
yes, I mean this file. I want to look how it works and I try to find an alternative to SignalR

**Comment by MagicAndre1981** [comment]
I opened a [2nd issue](https://github.com/SignalGo/SignalGoAddServiceReference-net/issues/2) because I got compile errors and this is why I looked in the generated `Reference.cs`.

If I run R# code cleanups it would also touch the file and modify it, so it would be better to have short version all time. That's why an option would be nice, which can be off by default.

**Comment by Ali-YousefiTelori** [comment]
its easy to migrate from signalR to signalgo, if you has projects you wrote with signalR you don't need changes more to convert it from signalR to signalgo,
SignalGo is not dynamically calls client services like signalR its more powerfull, for example your client service methods can send results from client to server when you call the callback services.

I saw your issuse and answered that.

**Comment by MagicAndre1981** [comment]
ok, the [code is now better](https://github.com/SignalGo/SignalGoAddServiceReference-net/issues/2#issuecomment-496215571).

But I still would like to have options add an empty line between the generated methods and an option avoid the full namespace for types.

**Comment by Ali-YousefiTelori** [comment]
Can you explain me why we should add this feature?
Thank You

**Comment by MagicAndre1981** [comment]
because everyone has different code formatting requirements.

I need options for :

- add empty line between the generated methods 
- avoid the full namespace for types
- put all generated classes/interface in seperate .cs file (currently everything is put into 1 large file which is horrible to read and you can't find anything in this large .cs)
- configure intent (you use 8 in generated code)

This is what I noticed after trying to get the lib working (which I still sturggle after 2 days)

**Comment by Ali-YousefiTelori** [comment]
Ok,
I don't undrestand completely your options 1,2,4 if you send me an example I will add those features.

**Comment by MagicAndre1981** [comment]
sorry, they are self explaining

in the [demo](https://github.com/SignalGo/signalgo-samples/blob/master/CSharp%20Client%20Sample/CSharpClientSample/Connected%20Services/MyTestServices/Reference.cs#L56) you see that all methods are added directly after each other and I want a new line, while scrolling in code you are lost without any empty lines.

**Comment by Ali-YousefiTelori** [comment]
You mean you want its must be "Clean" or "Formatted" codes, right?

**Comment by MagicAndre1981** [comment]
yes, let users format code we want it. I'm lost in the code [while trying to get the lib working](https://github.com/SignalGo/SignalGo-full-net/issues/8)
