### ISSUE TITLE
async issues with client generation

### ISSUE THREAD

**Issue by MagicAndre1981** [SignalGo/SignalGoAddServiceReference-net#2]
If I declare this my service:

```
public User LogOn(string userName, string password)
{
      return foo
}

public async Task<User> LogOnAsync(string userName, string password)
{
     return await foo
}
```

and let the extension generate the client I get issues with the async generation.

If I don't select Generate async I generates 2 methods, but both are sync:

```
User LogOn(string userName, string password);
User LogOnAsync(string userName, string password);
```

If I tell the extension to generate async it creates 3 methods and one confusing with 2 Async in name and the sync method still has Async in name.

```
Task<User> LogOnAsync(string userName, string password);
User LogOnAsync(string userName, string password);
Task<User> LogOnAsyncAsync(string userName, string password);
```

**Comment by Ali-YousefiTelori** [comment]
Thank you for your issuse,
If you are using those methods in server side you don't need to make two methods with sync and async names, because logics are one and anyway client side will has sync and async methods, can you tell me why you want have both of sync and async methods in one service server side?

**Comment by MagicAndre1981** [comment]
I have R# configured to warn if async method doesn't have Async in name.

The reason I have both is compatiblity with old Desktop program. Async was later added for usage with Xamarin Forms apps.

So should I only declase the sync versions? Because of the missing documentation of SignalGo it is difficult to start working with your lib. It is trial & error and see how it goes.

**Comment by Ali-YousefiTelori** [comment]
In server side you have to use one of async or sync version of your method, in client side signalgo will generate both of them for services and async methods has "Async" in the name.but if you are using old version of .net that has not async, you can uncheck generate async methods in signalgo extension when you are add your service, or you can right click on you references.cs file and select config signalgo service and unchek it.

but the problem is R# warn to you, I don't know why because signalgo will add "Async" word in end of method name like "Login" for sync methods and "LoginAsync" for async method. so why it warn to you?

**Comment by Ali-YousefiTelori** [comment]
if you have problem for naming server side method name, I wil check it and fix the problem for Async methods naming,

**Comment by MagicAndre1981** [comment]
The server side async are in my case real async, I call async methods of EF6 to query data, while sync version calls sync methods of EF6. So it looks like you wrap the sync version into async which is not that good.

**Comment by Ali-YousefiTelori** [comment]
Yes, you right, i fixed this issuse in new version of signalgo extension, pls update your signalgo extension and name your server side method to async like "LoginAsync" then update your client side service.
pls tell me if your issuse fixed.
Thank you.

**Comment by MagicAndre1981** [comment]
ok, with 4.6.3 the AsyncAsync is fixed, but I now have the 2 methods duplicated in `Reference.cs` (2 times LogOn and 2 times LogOnAsync and so I still can't compile the code)

```
Connected Services\SignalGoProvider\Reference.cs(104,55,104,60): error CS0111: Type 'IFooService' already defines a member called 'LogOn' with the same parameter types
Connected Services\SignalGoProvider\Reference.cs(105,61,105,71): error CS0111: Type 'IFooService' already defines a member called 'LogOnAsync' with the same parameter types
```

**Comment by Ali-YousefiTelori** [comment]
Are you made two methods with same logic and name? I think you should remove one of them on your server side, use async or sync, not both of them.
Because in signalgo structre you don't need to make duplicate methods when you have same logic, signalgo generator will make both of async and sync in client side for you.

**Comment by MagicAndre1981** [comment]
but as I wrote before, this looks like you wrap the sync version into async method. They do the same, but 1 is old school sync and 1 uses async at all. I want to have both and test them to see which works better. In SignalR your way causes deadlocks and hangs

**Comment by Ali-YousefiTelori** [comment]
If you want have sync and async method in server side, you can uncheck "Generate async methods" in signalgo configoration.but if you want have async and sync in client side i have no idea how can i handle this way? you have Login and LoginAsync in server side so what methods should create in client side with sync and async names?

![Untitled](https://user-images.githubusercontent.com/5262218/58416825-1bb8f000-8098-11e9-9960-0321a1f04729.png)

**Comment by MagicAndre1981** [comment]
when I do this I have 2 times LogOn (as sync version). So last version duplicates all generated methods

**Comment by MagicAndre1981** [comment]
In GenerateOneWayMethod check for ReturnTypeName == Task and if methodInfo.Name ends with Async and simple generate the async method.

Your checkbox should be named "Generate async wrappers for sync methods", this expains it better for starters like me.

_Edit_

we posted the same time.

ok I'll wait until Visual Studio offers the update and test it.

**Comment by Ali-YousefiTelori** [comment]
Ok I made new version of signalgo extension with new setting you can check it, it will ignore automatically add methods and just make real method that you added on server, pls check and update you extension and tell me if you problem fixed,
Thank you.

![Untitled](https://user-images.githubusercontent.com/5262218/58419390-bcf77480-809f-11e9-9285-a939e7ff8c4f.png)

**Comment by MagicAndre1981** [comment]
great, last version works and I have now the correct code.

I still have some issues with generated code.

I have a duplicated `using System;` entry:

![image](https://user-images.githubusercontent.com/8274816/58422792-cd095700-8093-11e9-9cbd-00b2c0a403d5.png)

> Connected Services\SignalGoProvider\Reference.cs(15,7,15,13): warning CS0105: The using directive for 'System' appeared previously in this namespace

**Comment by Ali-YousefiTelori** [comment]
I updated signalgo extension you can updated it now.
Tell me if issue fixed.
Thank You

**Comment by MagicAndre1981** [comment]
yes, 4.6.3.3 fixes the doubled using and async generation now also works as I expect
